services:
  app:
    image: shrimpers-trust-cli:latest # Replace with your actual image
    container_name: shrimpers-trust-cli
    ports:
      - "3000:3000" # Map container port 8080 to host port 8080
    env_file:
      # Reference an external .env file for additional variables
      - .env
    restart: always # Ensure the container restarts on failure
    command: ./app api start
