NAMES_TO_GENDER = {
    "Alfred": "Male", "Francis": "Male", "Samantha": "Female", "Jean": "Female",
    "Elizabeth": "Female", "Tony": "Male", "Derrick": "Male", "Lorna": "Female",
    "Matt": "Male", "Maxwell": "Male", "John": "Male", "Michael": "Male",
    "Alex": "Unknown", "Chris": "Unknown", "Conor": "Male", "Daniel": "Male",
    "Tania": "Female", "Marion": "Female", "Nina": "Female", "Maria": "Female",
    "Mary": "Female", "Judy": "Female", "Rosemary": "Female", "Nick": "Male",
    "Billy": "Male", "Selwyn": "Male", "Miranda": "Female", "Roy": "Male",
    "Max": "Male", "Miller": "Male", "Andrew": "Male", "Samuel": "Male",
    "Zach": "Male", "Judith": "Female", "Pamela": "Female", "Jemma": "Female",
    "Dom": "Male", "Stanley": "Male", "Symon": "Male", "Ronald": "Male",
    "Kelly": "Unknown", "Sandra": "Female", "Ken": "Male", "Karen": "Female",
    "Amber": "Female", "Gary": "Male", "Edan": "Male", "Dylan": "Male",
    "Edward": "Male", "Ritchie": "Male", "Sophie": "Female", "Helen": "Female",
    "Joseph": "Male", "Simon": "Male", "Mrs. A": "Female", "Murray": "Male",
    "Toby": "Male", "Adrian": "Male", "Miles": "Male", "Russell": "Male",
    "Peter": "Male", "Jon": "Male", "Gerald": "Male", "Maureen": "Female",
    "Alaric": "Male", "Clive": "Male", "Alan John": "Male", "Dean": "Male",
    "Grace": "Female", "Ginny": "Female", "Stephanie": "Female", "David": "Male",
    "Sean": "Male", "Kenneth": "Male", "Claire": "Female", "Irwin": "Male",
    "Seb": "Male", "Paula": "Female", "Lydia": "Female", "Shane": "Male",
    "Piers": "Male", "Lorraine": "Female", "Kristoffer": "Male", "Brad": "Male",
    "Zoe": "Female", "Royston": "Male", "Carl": "Male", "Baz": "Male",
    "Jane": "Female", "Gavin": "Male", "William": "Male", "Perry": "Male",
    "Bob": "Male", "Alfie": "Male", "Karyn": "Female", "Jamal": "Male",
    "Deborah": "Female", "Gregory": "Male", "Malcolm": "Male", "Dirk": "Male",
    "Patricia": "Female", "Andee": "Unknown", "Victor": "Male", "Kevan": "Male",
    "Ash": "Unknown", "Kirsty": "Female", "Gordon": "Male", "Lauren": "Female",
    "Morgan": "Unknown", "Adam": "Male", "Ann": "Female", "Oliver": "Male",
    "Jevon": "Male", "Niki": "Unknown", "Jarl": "Male", "Greg": "Male",
    "Trevor": "Male", "Dominic": "Male", "Hannah": "Female", "Lee": "Unknown",
    "Roger": "Male", "Raymond": "Male", "Sue": "Female", "Lyndia": "Female",
    "Sonny": "Male", "Lynn": "Unknown", "Pete": "Male", "Jenny": "Female",
    "Mandy": "Female", "Findlay": "Male", "Marc": "Male", "Paul": "Male",
    "Oliver-Lee": "Male", "Guy": "Male", "Katie": "Female", "Kian": "Male",
    "Dr. Malcolm": "Male", "Caroline": "Female", "Robert": "Male", "Rex": "Male",
    "Neal": "Male", "Patsy": "Female", "Wendy": "Female", "Philip": "Male",
    "Andy": "Male", "Kurtis": "Male", "Michelle": "Female", "Neil": "Male",
    "Susannah": "Female", "Pipa": "Female", "Harry": "Male", "Mitch": "Male",
    "Ben": "Male", "Margaret": "Female", "Ilean": "Female", "Geoffrey": "Male",
    "Theo": "Male", "Stuart": "Male", "Rebecca": "Female", "Christopher": "Male",
    "Howard": "Male", "Rod": "Male", "Emrys": "Male", "Denis": "Male",
    "Tommy": "Male", "Didier": "Male", "Danny": "Male", "Carole": "Female",
    "Martyn": "Male", "Kay": "Female", "Jay": "Unknown", "Jim": "Male",
    "Gaylyn": "Female", "Deryck": "Male", "Emma": "Female", "Harvey": "Male",
    "Dave": "Male", "Carolyn": "Female", "Josh": "Male", "Aaron": "Male",
    "Gillian": "Female", "Dan": "Male", "Therese": "Female", "Jackie": "Unknown",
    "Frank": "Male", "Colin": "Male", "Sarah": "Female", "Carol": "Female",
    "Archie": "Male", "Craig": "Male", "Ed": "Male", "Jonathan": "Male",
    "Gareth": "Male", "Thomas": "Male", "Veronica": "Female", "Leon": "Male",
    "Lew": "Male", "Eileen": "Female", "Brett": "Male", "Joan": "Female",
    "Mark": "Male", "Callum": "Male", "Briony": "Female", "Anna": "Female",
    "Rick": "Male", "Tom": "Male", "Angus": "Male", "Jeff": "Male",
    "Anne": "Female", "Brian": "Male", "Jon-Paul": "Male", "Mr. J.M.": "Male",
    "Glen": "Male", "Eric": "Male", "James": "Male", "Ian": "Male",
    "Niamh": "Female", "Irene": "Female", "Benjamin": "Male", "Helen": "Female",
    "Keeley": "Female", "Iain": "Male", "Richard": "Male", "David": "Male",
    "Suzanne": "Female", "Rodney": "Male", "Terence": "Male", "Nicholas": "Male",
    "Martin": "Male", "Keith": "Male", "Nicola": "Female", "Bill": "Male",
    "Steven": "Male", "Sara": "Female", "Edwin": "Male", "Beverley": "Female",
    "Aubrey": "Male", "Jacqueline": "Female", "Lawrence": "Male", "Cassie": "Female",
    "Steve": "Male", "Rona": "Female", "Wayne": "Male", "George": "Male",
    "Susan": "Female", "Apiradee": "Female", "Yann": "Male", "Tracy": "Female",
    "Lisa": "Female", "Barbara": "Female", "Terence": "Male", "Julie": "Female",
    "Geoff": "Male", "Dale": "Male", "Jeremy": "Male", "Lesley": "Female",
    "Owen": "Male", "Jo-Anna": "Female", "Sidney": "Male", "Clifford": "Male",
    "Alison": "Female", "Leslie": "Unknown", "Derek": "Male", "Kizzy": "Female",
    "Diane": "Female", "Ruari": "Male", "Jack": "Male", "Louis": "Male",
    "Melvyn": "Male", "J.L.": "Unknown", "Scott": "Male", "Linda": "Female",
    "Jake": "Male", "Joshua": "Male", "Finley": "Unknown", "Liz": "Female",
    "Bryan": "Male", "Norman": "Male", "Sam": "Unknown", "Lee": "Unknown",
    "Liam": "Male", "Kerr": "Male", "Ron": "Male", "Mandie": "Female",
    "Duncan": "Male", "Mark": "Male", "Mr. B": "Male", "Maurice": "Male",
    "Laurence": "Male", "Berry": "Unknown", "Tara": "Female", "Ashley": "Unknown",
    "Charles": "Male", "Pauline": "Female", "Martyn": "Male", "Amanda-Jane": "Female",
    "Anthony": "Male", "Patrick": "Male", "Brian": "Male", "Matthew": "Male",
    "Harrison": "Male", "Darren": "Male", "Nikki": "Unknown", "Alec": "Male",
    "Teresa": "Female", "Joe": "Male", "Gill": "Female", "Harley": "Unknown",
    "Ross": "Male", "Bradley": "Male", "Graham": "Male", "Rob": "Male",
    "Connor": "Male", "Ryan": "Male", "Karl": "Male", "Phillip": "Male",
    "Stephen": "Male", "Nigel": "Male", "Coral": "Female", "Louisa": "Female",
    "Clare": "Female", "Nathan": "Male", "Stewart": "Male", "Jimmy": "Male",
    "Neill": "Male", "Giovanni": "Male", "Freddie": "Male", "Louise": "Female",
    "Angela": "Female", "Doug": "Male", "Jo-Anne": "Female", "Kath": "Female",
    "Baylee": "Unknown", "Dennis": "Male", "Amy": "Female", "Terry": "Unknown",
    "Mark 'Ozzie'": "Male", "Tina": "Female", "Graeme": "Male", "Bobby": "Male",
    "Garry": "Male", "Leigh": "Unknown", "Danielle": "Female", "Denys": "Male",
    "Daryl": "Male", "Euan": "Male", "Alice": "Female", "Jeffrey": "Male",
    "Yvonne": "Female", "Jennifer": "Female", "Holly": "Female", "Bharat": "Male",
    "Harriet Joy": "Female", "Fiona": "Female", "Grant": "Male", "Diarmaid": "Male",
    "Charlotte": "Female", "Deison Luigi": "Male", "Phil": "Male", "Vic": "Male",
    "Greg": "Male", "Fred": "Male", "Julian": "Male", "Katherine": "Female",
    "Jason": "Male", "Neill David": "Male", "Kathleen": "Female", "Jan": "Unknown",
    "Peter John": "Male", "Aiden": "Male", "Sheila": "Female", "Rachel": "Female",
    "Jody": "Unknown", "Tim": "Male", "Christine": "Female", "Ollie": "Male",
    "Lynne": "Female", "Hugh": "Male", "Lewis": "Male", "Brenda": "Female",
    "Robin": "Unknown", "Mrs. J": "Female", "Sharon": "Female", "Tyrinne": "Unknown",
    "Kevin": "Male", "Cheryl": "Female", "Dani": "Unknown", "Mick": "Male",
    "Jo": "Unknown", "Jerry": "Male", "Tracey": "Female", "Alistair": "Male",
    "Annette": "Female", "Len": "Male", "Jamie": "Unknown", "Tricia": "Female",
    "Lucy": "Female", "Mike": "Male", "Laura": "Female", "Alan": "Male",
    "Curtis": "Male", "Barry": "Male", "Benedict": "Male", "Eddie-Richard": "Male",
    "Ricky": "Male", "Vicky": "Female", "Warren": "Male", "Bethany": "Female",
    "Justin": "Male", "Bernard": "Male", "Gino": "Male", "Victoria": "Female",
    "Johanne": "Female", "Joel": "Male", "Luke": "Male", "Geoff": "Male",
    "Ewan": "Male", "Charlie": "Unknown", "Joanne": "Female", "Gaye": "Female",
    "Arthur": "Male", "Donna": "Female", "Glenn": "Male", "Kerry": "Unknown",
    "Hils": "Female", "Alexander": "Male"
}